[package]
name = "shutup-rs"
version = "0.1.0"
authors = ["Artur Sinila <opensource@logarithmus.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13"
hound = "3"
anyhow = "1"
clap = "2"
